name: nekomimi
description: "A new Flutter project."

publish_to: 'github'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2

  provider: ^6.1.2

  url_launcher: ^6.3.0

  font_awesome_flutter: ^10.7.0

  flutter_bloc: ^8.1.6

  flutter_screenutil: ^5.9.3

  flutter_localization: ^0.2.2

  network_info_plus: ^6.0.1

  http: ^1.2.2

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  ios: false
  web: false
  color: "#5cc9fe"
  android_12:
    color: "#5cc9fe"

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/play_store_512.png"
  adaptive_icon_background: "#5cc9fe"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
  - family: ArabicFont
    fonts:
      - asset: assets/fonts/ar/Tajawal-Regular.ttf

  - family: EnglishFont
    fonts:
      - asset: assets/fonts/en/Overlock-Regular.ttf

  - family: JapaneseFont
    fonts:
      - asset: assets/fonts/jp/YujiSyuku-Regular.ttf

flutter_intl:
  enabled: true
